# Name of our action
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          fetch-tags: true

      # - name: Build
      #   uses: ./libMvrGdtf/.github/actions/build-linux

      - name: Add .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PKG_KEY}}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PKG_KEY }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_PKG_KEY}}
        working-directory: libMvrGdtf 
        run: |
          npm install
          npm run release
